FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3.10 python3-pip python3-venv git git-lfs curl wget cmake vim libopenmpi-dev
RUN git lfs install

# Install NVIDIA CUDA keyring
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-keyring_1.1-1_all.deb
RUN rm cuda-keyring_1.1-1_all.deb
RUN apt-get update

# start with empty LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=

# CUDA 12.6 with a bunch of tools
RUN apt-get install -y cuda-toolkit-12-6 cuda-cudart-12-6 cuda-compiler-12-6
ENV LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/local/cuda-12.6/bin:$PATH
RUN python3 -m pip install cuda-python==12.6.2.post1

# TensorRT 10.7
COPY TensorRT-10.7.0.23.l4t.aarch64-gnu.cuda-12.6.tar.gz /opt/
RUN tar -xzvf /opt/TensorRT-10.7.0.23.l4t.aarch64-gnu.cuda-12.6.tar.gz -C /opt/
RUN rm /opt/TensorRT-10.7.0.23.l4t.aarch64-gnu.cuda-12.6.tar.gz
WORKDIR /opt/TensorRT-10.7.0.23/python
RUN python3 -m pip install tensorrt-10.7.0-cp310-none-linux_aarch64.whl
WORKDIR /
RUN cp /opt/TensorRT-10.7.0.23/include/* /usr/include/aarch64-linux-gnu/
RUN cp -R /opt/TensorRT-10.7.0.23/lib/* /usr/lib/aarch64-linux-gnu/
ENV TRT_PATH=/opt/TensorRT-10.7.0.23
ENV PATH=$TRT_PATH/bin:$PATH
ENV LD_LIBRARY_PATH=$TRT_PATH/lib:$LD_LIBRARY_PATH

# NCCL
RUN apt-get install -y build-essential
RUN git clone --depth=1 --branch=v2.29.3-1 https://github.com/NVIDIA/nccl
WORKDIR /nccl
RUN make -j2 src.build NVCC_GENCODE="-gencode=arch=compute_87,code=sm_87"
RUN cp -a build/include/* /usr/include/
RUN cp -a build/lib/* /usr/lib/aarch64-linux-gnu/
RUN ldconfig
WORKDIR /
RUN rm -rf nccl

# PyTorch 2.5.0
RUN pip install --no-deps https://developer.download.nvidia.com/compute/redist/jp/v61/pytorch/torch-2.5.0a0+872d972e41.nv24.08.17622132-cp310-cp310-linux_aarch64.whl

# TensorRT-LLM 0.14.0
RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1
ENV SAVED_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$LD_LIBRARY_PATH
RUN git clone https://github.com/NVIDIA/TensorRT-LLM.git
WORKDIR /TensorRT-LLM
RUN git checkout v0.14.0
RUN git submodule update --init --recursive
RUN git lfs pull
RUN sed -i 's/tensorrt~=/# &/' requirements.txt
RUN sed -i 's/torch>=/# &/' requirements.txt
RUN sed -i 's/pynvml.__version__/getattr(pynvml,"__version__","99.0.0")/' /TensorRT-LLM/tensorrt_llm/profiler.py
RUN sed -i 's/pynvml.__version__/getattr(pynvml,"__version__","99.0.0")/' /TensorRT-LLM/tensorrt_llm/auto_parallel/cluster_info.py
RUN apt install -y ccache
RUN pip show torch | grep ^Version | cut -d' ' -f2 | xargs -I{} sh -c 'echo "torch=={}"' >/tmp/constraints.txt
ENV PIP_CONSTRAINT=/tmp/constraints.txt
RUN apt install -y libcudnn9-cuda-12 libcudnn9-dev-cuda-12 libopenblas-dev libcusparselt0 libcusparselt-dev
COPY libnvdla_compiler.so /usr/lib/aarch64-linux-gnu/
COPY libnvcudla.so /usr/lib/aarch64-linux-gnu/
RUN python3 ./scripts/build_wheel.py --build_type Release -a "87" --install --job_count 4 --use_ccache
ENV PIP_CONSTRAINT=
RUN pip install /TensorRT-LLM/build/tensorrt_llm-0.14.0-cp310-cp310-linux_aarch64.whl
RUN ldconfig -n /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs
RUN rm /usr/local/cuda/lib64/stubs/libcuda.so.1
ENV LD_LIBRARY_PATH=$SAVED_LD_LIBRARY_PATH
WORKDIR /

# Rust (could be moved to earlier stage)
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN source ~/.cargo/ENV
RUN apt-get install -y pkg-config libasound2-dev libpulse-dev

# ONNX runtime
RUN git clone --recursive https://github.com/microsoft/onnxruntime.git -b v1.21.0
WORKDIR /onnxruntime
RUN ./build.sh --config Release --build_shared_lib --parallel 4 --use_cuda --cuda_home /usr/local/cuda --use_tensorrt --tensorrt_home /usr/lib/aarch64-linux-gnu --cudnn_home /usr/lib/aarch64-linux-gnu
WORKDIR build/Linux/Release
RUN cp * /usr/local/lib/
WORKDIR /
RUN rm -rf onnxruntime
