FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3.10 python3-pip python3-venv git git-lfs curl wget
RUN git lfs install

# Install NVIDIA CUDA keyring
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-keyring_1.1-1_all.deb
RUN rm cuda-keyring_1.1-1_all.deb
RUN apt-get update

# start with empty LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=

# CUDA 12.6 with a bunch of tools
RUN apt-get install -y cuda-toolkit-12-6 cuda-cudart-12-6 cuda-compiler-12-6
ENV LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/local/cuda-12.6/bin:$PATH
RUN python3 -m pip install cuda-python==12.6.2.post1

# TensorRT 10.7
COPY TensorRT-10.7.0.23.l4t.aarch64-gnu.cuda-12.6.tar.gz /opt/
RUN tar -xzvf /opt/TensorRT-10.7.0.23.l4t.aarch64-gnu.cuda-12.6.tar.gz -C /opt/
RUN rm /opt/TensorRT-10.7.0.23.l4t.aarch64-gnu.cuda-12.6.tar.gz
WORKDIR /opt/TensorRT-10.7.0.23/python
RUN python3 -m pip install tensorrt-10.7.0-cp310-none-linux_aarch64.whl
WORKDIR /
RUN cp /opt/TensorRT-10.7.0.23/include/* /usr/include/aarch64-linux-gnu/
RUN cp -R /opt/TensorRT-10.7.0.23/lib/* /usr/lib/aarch64-linux-gnu/
ENV TRT_PATH=/opt/TensorRT-10.7.0.23
ENV PATH=$TRT_PATH/bin:$PATH
ENV LD_LIBRARY_PATH=$TRT_PATH/lib:$LD_LIBRARY_PATH

# NCCL
RUN apt-get install -y build-essential
RUN git clone --depth=1 --branch=v2.29.3-1 https://github.com/NVIDIA/nccl
WORKDIR /nccl
RUN make -j2 src.build NVCC_GENCODE="-gencode=arch=compute_87,code=sm_87"
RUN cp -a build/include/* /usr/include/
RUN cp -a build/lib/* /usr/lib/aarch64-linux-gnu/
RUN ldconfig
WORKDIR /
RUN rm -rf nccl

# more tools
RUN apt-get install -y cmake vim libopenmpi-dev

# TensorRT-LLM 0.14.0
RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1
ENV SAVED_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$LD_LIBRARY_PATH
RUN git clone https://github.com/NVIDIA/TensorRT-LLM.git
WORKDIR /TensorRT-LLM
RUN git checkout v0.14.0
RUN git submodule update --init --recursive
RUN git lfs pull
RUN sed -i 's/tensorrt~=/# &/' requirements.txt
RUN sed -i 's/pynvml.__version__/getattr(pynvml,"__version__","99.0.0")/' /TensorRT-LLM/tensorrt_llm/profiler.py
#RUN python3 ./scripts/build_wheel.py --build_type Release -a "87" --install --job_count 4
#RUN rm /usr/local/cuda/lib64/stubs/libcuda.so.1
#ENV LD_LIBRARY_PATH=$SAVED_LD_LIBRARY_PATH
#WORKDIR /
